/*
 jQuery UI - v1.10.4 - 2014-04-13
 http://jqueryui.com
 Includes: jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.position.js, jquery.ui.autocomplete.js, jquery.ui.menu.js
 Copyright 2014 jQuery Foundation and other contributors; Licensed MIT */
var SAS;
(function(b,a){function c(a,c){var f,h,g,e=a.nodeName.toLowerCase();return"area"===e?(f=a.parentNode,h=f.name,a.href&&h&&"map"===f.nodeName.toLowerCase()?(g=b("img[usemap\x3d#"+h+"]")[0],!!g&&d(g)):!1):(/input|select|textarea|button|object/.test(e)?!a.disabled:"a"===e?a.href||c:c)&&d(a)}function d(a){return b.expr.filters.visible(a)&&!b(a).parents().addBack().filter(function(){return"hidden"===b.css(this,"visibility")}).length}var e=0,g=/^ui-id-\d+$/;b.ui=b.ui||{};b.extend(b.ui,{version:"1.10.4",keyCode:{BACKSPACE:8,
COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38}});b.fn.extend({focus:function(a){return function(c,f){return"number"==typeof c?this.each(function(){var a=this;setTimeout(function(){b(a).focus();f&&f.call(a)},c)}):a.apply(this,arguments)}}(b.fn.focus),scrollParent:function(){var a;return a=b.ui.ie&&/(static|relative)/.test(this.css("position"))||
/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0),/fixed/.test(this.css("position"))||!a.length?b(document):a},zIndex:function(c){if(c!==a)return this.css("zIndex",c);if(this.length){var f,
g;for(c=b(this[0]);c.length&&c[0]!==document;){if(f=c.css("position"),("absolute"===f||"relative"===f||"fixed"===f)&&(g=parseInt(c.css("zIndex"),10),!isNaN(g)&&0!==g))return g;c=c.parent()}}return 0},uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++e)})},removeUniqueId:function(){return this.each(function(){g.test(this.id)&&b(this).removeAttr("id")})}});b.extend(b.expr[":"],{data:b.expr.createPseudo?b.expr.createPseudo(function(a){return function(c){return!!b.data(c,a)}}):
function(a,c,g){return!!b.data(a,g[3])},focusable:function(a){return c(a,!isNaN(b.attr(a,"tabindex")))},tabbable:function(a){var f=b.attr(a,"tabindex"),g=isNaN(f);return(g||0<=f)&&c(a,!g)}});b("\x3ca\x3e").outerWidth(1).jquery||b.each(["Width","Height"],function(c,g){function f(a,c,f,g){return b.each(h,function(){c-=parseFloat(b.css(a,"padding"+this))||0;f&&(c-=parseFloat(b.css(a,"border"+this+"Width"))||0);g&&(c-=parseFloat(b.css(a,"margin"+this))||0)}),c}var h="Width"===g?["Left","Right"]:["Top",
"Bottom"],d=g.toLowerCase(),e={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+g]=function(c){return c===a?e["inner"+g].call(this):this.each(function(){b(this).css(d,f(this,c)+"px")})};b.fn["outer"+g]=function(a,c){return"number"!=typeof a?e["outer"+g].call(this,a):this.each(function(){b(this).css(d,f(this,a,!0,c)+"px")})}});b.fn.addBack||(b.fn.addBack=function(b){return this.add(null==b?this.prevObject:this.prevObject.filter(b))});
b("\x3ca\x3e").data("a-b","a").removeData("a-b").data("a-b")&&(b.fn.removeData=function(a){return function(c){return arguments.length?a.call(this,b.camelCase(c)):a.call(this)}}(b.fn.removeData));b.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());b.support.selectstart="onselectstart"in document.createElement("div");b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(b){b.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});
b.extend(b.ui,{plugin:{add:function(a,c,g){var f;a=b.ui[a].prototype;for(f in g)a.plugins[f]=a.plugins[f]||[],a.plugins[f].push([c,g[f]])},call:function(b,a,c){var f=b.plugins[a];if(f&&b.element[0].parentNode&&11!==b.element[0].parentNode.nodeType)for(a=0;f.length>a;a++)b.options[f[a][0]]&&f[a][1].apply(b.element,c)}},hasScroll:function(a,c){if("hidden"===b(a).css("overflow"))return!1;c=c&&"left"===c?"scrollLeft":"scrollTop";var f=!1;return 0<a[c]?!0:(a[c]=1,f=0<a[c],a[c]=0,f)}})})(jQuery);
(function(b,a){var c=0,d=Array.prototype.slice,e=b.cleanData;b.cleanData=function(a){for(var c,g=0;null!=(c=a[g]);g++)try{b(c).triggerHandler("remove")}catch(k){}e(a)};b.widget=function(c,f,h){var g={},d=c.split(".")[0];c=c.split(".")[1];var e=d+"-"+c;h||(h=f,f=b.Widget);b.expr[":"][e.toLowerCase()]=function(a){return!!b.data(a,e)};b[d]=b[d]||{};var p=b[d][c];var q=b[d][c]=function(b,c){return this._createWidget?(arguments.length&&this._createWidget(b,c),a):new q(b,c)};b.extend(q,p,{version:h.version,
_proto:b.extend({},h),_childConstructors:[]});var v=new f;v.options=b.widget.extend({},v.options);b.each(h,function(c,d){return b.isFunction(d)?(g[c]=function(){var b=function(){return f.prototype[c].apply(this,arguments)},a=function(b){return f.prototype[c].apply(this,b)};return function(){var c,f=this._super,g=this._superApply;return this._super=b,this._superApply=a,c=d.apply(this,arguments),this._super=f,this._superApply=g,c}}(),a):(g[c]=d,a)});q.prototype=b.widget.extend(v,{widgetEventPrefix:p?
v.widgetEventPrefix||c:c},g,{constructor:q,namespace:d,widgetName:c,widgetFullName:e});p?(b.each(p._childConstructors,function(a,c){a=c.prototype;b.widget(a.namespace+"."+a.widgetName,q,c._proto)}),delete p._childConstructors):f._childConstructors.push(q);b.widget.bridge(c,q)};b.widget.extend=function(c){for(var f,g,e=d.call(arguments,1),m=0,l=e.length;l>m;m++)for(f in e[m])g=e[m][f],e[m].hasOwnProperty(f)&&g!==a&&(c[f]=b.isPlainObject(g)?b.isPlainObject(c[f])?b.widget.extend({},c[f],g):b.widget.extend({},
g):g);return c};b.widget.bridge=function(c,f){var g=f.prototype.widgetFullName||c;b.fn[c]=function(e){var h="string"==typeof e,k=d.call(arguments,1),p=this;return e=!h&&k.length?b.widget.extend.apply(null,[e].concat(k)):e,h?this.each(function(){var f,d=b.data(this,g);return d?b.isFunction(d[e])&&"_"!==e.charAt(0)?(f=d[e].apply(d,k),f!==d&&f!==a?(p=f&&f.jquery?p.pushStack(f.get()):f,!1):a):b.error("no such method '"+e+"' for "+c+" widget instance"):b.error("cannot call methods on "+c+" prior to initialization; attempted to call method '"+
e+"'")}):this.each(function(){var a=b.data(this,g);a?a.option(e||{})._init():b.data(this,g,new f(e,this))}),p}};b.Widget=function(){};b.Widget._childConstructors=[];b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"\x3cdiv\x3e",options:{disabled:!1,create:null},_createWidget:function(a,f){f=b(f||this.defaultElement||this)[0];this.element=b(f);this.uuid=c++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=b.widget.extend({},this.options,this._getCreateOptions(),
a);this.bindings=b();this.hoverable=b();this.focusable=b();f!==this&&(b.data(f,this.widgetFullName,this),this._on(!0,this.element,{remove:function(b){b.target===f&&this.destroy()}}),this.document=b(f.style?f.ownerDocument:f.document||f),this.window=b(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:b.noop,_getCreateEventData:b.noop,_create:b.noop,_init:b.noop,destroy:function(){this._destroy();
this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(b.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:b.noop,widget:function(){return this.element},option:function(c,f){var g,d,e=c;if(0===
arguments.length)return b.widget.extend({},this.options);if("string"==typeof c)if(e={},g=c.split("."),c=g.shift(),g.length){var l=e[c]=b.widget.extend({},this.options[c]);for(d=0;g.length-1>d;d++)l[g[d]]=l[g[d]]||{},l=l[g[d]];if(c=g.pop(),1===arguments.length)return l[c]===a?null:l[c];l[c]=f}else{if(1===arguments.length)return this.options[c]===a?null:this.options[c];e[c]=f}return this._setOptions(e),this},_setOptions:function(b){for(var a in b)this._setOption(a,b[a]);return this},_setOption:function(b,
a){return this.options[b]=a,"disabled"===b&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!a).attr("aria-disabled",a),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus")),this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(c,f,d){var g,e=this;"boolean"!=typeof c&&(d=f,f=c,c=!1);d?(f=g=b(f),this.bindings=this.bindings.add(f)):(d=f,f=this.element,g=
this.widget());b.each(d,function(d,h){function k(){return c||!0!==e.options.disabled&&!b(this).hasClass("ui-state-disabled")?("string"==typeof h?e[h]:h).apply(e,arguments):a}"string"!=typeof h&&(k.guid=h.guid=h.guid||k.guid||b.guid++);var m=d.match(/^(\w+)\s*(.*)$/);d=m[1]+e.eventNamespace;(m=m[2])?g.delegate(m,d,k):f.bind(d,k)})},_off:function(b,a){a=(a||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;b.unbind(a).undelegate(a)},_delay:function(b,a){var c=this;return setTimeout(function(){return("string"==
typeof b?c[b]:b).apply(c,arguments)},a||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){b(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){b(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){b(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){b(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(a,c,d){var f,
e=this.options[a];if(d=d||{},c=b.Event(c),c.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase(),c.target=this.element[0],a=c.originalEvent)for(f in a)f in c||(c[f]=a[f]);return this.element.trigger(c,d),!(b.isFunction(e)&&!1===e.apply(this.element[0],[c].concat(d))||c.isDefaultPrevented())}};b.each({show:"fadeIn",hide:"fadeOut"},function(a,c){b.Widget.prototype["_"+a]=function(f,d,e){"string"==typeof d&&(d={effect:d});var g=d?!0===d||"number"==typeof d?c:d.effect||c:a;d=d||
{};"number"==typeof d&&(d={duration:d});var h=!b.isEmptyObject(d);d.complete=e;d.delay&&f.delay(d.delay);h&&b.effects&&b.effects.effect[g]?f[a](d):g!==a&&f[g]?f[g](d.duration,d.easing,e):f.queue(function(c){b(this)[a]();e&&e.call(f[0]);c()})}})})(jQuery);
(function(b,a){function c(a,b,c){return[parseFloat(a[0])*(q.test(a[0])?b/100:1),parseFloat(a[1])*(q.test(a[1])?c/100:1)]}function d(a){var c=a[0];return 9===c.nodeType?{width:a.width(),height:a.height(),offset:{top:0,left:0}}:b.isWindow(c)?{width:a.width(),height:a.height(),offset:{top:a.scrollTop(),left:a.scrollLeft()}}:c.preventDefault?{width:0,height:0,offset:{top:c.pageY,left:c.pageX}}:{width:a.outerWidth(),height:a.outerHeight(),offset:a.offset()}}b.ui=b.ui||{};var e,g=Math.max,f=Math.abs,h=
Math.round,k=/left|center|right/,m=/top|center|bottom/,l=/[\+\-]\d+(\.[\d]+)?%?/,p=/^\w+/,q=/%$/,v=b.fn.position;b.position={scrollbarWidth:function(){if(e!==a)return e;var c,d,f=b("\x3cdiv style\x3d'display:block;position:absolute;width:50px;height:50px;overflow:hidden;'\x3e\x3cdiv style\x3d'height:100px;width:auto;'\x3e\x3c/div\x3e\x3c/div\x3e"),g=f.children()[0];return b("body").append(f),c=g.offsetWidth,f.css("overflow","scroll"),d=g.offsetWidth,c===d&&(d=f[0].clientWidth),f.remove(),e=c-d},getScrollInfo:function(a){var c=
a.isWindow||a.isDocument?"":a.element.css("overflow-x"),d=a.isWindow||a.isDocument?"":a.element.css("overflow-y");c="scroll"===c||"auto"===c&&a.width<a.element[0].scrollWidth;return{width:"scroll"===d||"auto"===d&&a.height<a.element[0].scrollHeight?b.position.scrollbarWidth():0,height:c?b.position.scrollbarWidth():0}},getWithinInfo:function(a){a=b(a||window);var c=b.isWindow(a[0]);return{element:a,isWindow:c,isDocument:!!a[0]&&9===a[0].nodeType,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),
scrollTop:a.scrollTop(),width:c?a.width():a.outerWidth(),height:c?a.height():a.outerHeight()}}};b.fn.position=function(a){if(!a||!a.of)return v.apply(this,arguments);a=b.extend({},a);var e,r,w,y,t,x,A=b(a.of),q=b.position.getWithinInfo(a.within),C=b.position.getScrollInfo(q),z=(a.collision||"flip").split(" "),B={};return x=d(A),A[0].preventDefault&&(a.at="left top"),r=x.width,w=x.height,y=x.offset,t=b.extend({},y),b.each(["my","at"],function(){var b=(a[this]||"").split(" ");1===b.length&&(b=k.test(b[0])?
b.concat(["center"]):m.test(b[0])?["center"].concat(b):["center","center"]);b[0]=k.test(b[0])?b[0]:"center";b[1]=m.test(b[1])?b[1]:"center";var c=l.exec(b[0]);var d=l.exec(b[1]);B[this]=[c?c[0]:0,d?d[0]:0];a[this]=[p.exec(b[0])[0],p.exec(b[1])[0]]}),1===z.length&&(z[1]=z[0]),"right"===a.at[0]?t.left+=r:"center"===a.at[0]&&(t.left+=r/2),"bottom"===a.at[1]?t.top+=w:"center"===a.at[1]&&(t.top+=w/2),e=c(B.at,r,w),t.left+=e[0],t.top+=e[1],this.each(function(){var d,k=b(this),u=k.outerWidth(),m=k.outerHeight(),
l=parseInt(b.css(this,"marginLeft"),10)||0,x=parseInt(b.css(this,"marginTop"),10)||0,p=u+l+(parseInt(b.css(this,"marginRight"),10)||0)+C.width,D=m+x+(parseInt(b.css(this,"marginBottom"),10)||0)+C.height,n=b.extend({},t),v=c(B.my,k.outerWidth(),k.outerHeight());"right"===a.my[0]?n.left-=u:"center"===a.my[0]&&(n.left-=u/2);"bottom"===a.my[1]?n.top-=m:"center"===a.my[1]&&(n.top-=m/2);n.left+=v[0];n.top+=v[1];b.support.offsetFractions||(n.left=h(n.left),n.top=h(n.top));var E={marginLeft:l,marginTop:x};
b.each(["left","top"],function(c,d){b.ui.position[z[c]]&&b.ui.position[z[c]][d](n,{targetWidth:r,targetHeight:w,elemWidth:u,elemHeight:m,collisionPosition:E,collisionWidth:p,collisionHeight:D,offset:[e[0]+v[0],e[1]+v[1]],my:a.my,at:a.at,within:q,elem:k})});a.using&&(d=function(b){var c=y.left-n.left,d=c+r-u,e=y.top-n.top,h=e+w-m,l={target:{element:A,left:y.left,top:y.top,width:r,height:w},element:{element:k,left:n.left,top:n.top,width:u,height:m},horizontal:0>d?"left":0<c?"right":"center",vertical:0>
h?"top":0<e?"bottom":"middle"};u>r&&r>f(c+d)&&(l.horizontal="center");m>w&&w>f(e+h)&&(l.vertical="middle");l.important=g(f(c),f(d))>g(f(e),f(h))?"horizontal":"vertical";a.using.call(this,b,l)});k.offset(b.extend(n,{using:d}))})};b.ui.position={fit:{left:function(a,b){var c,d=b.within,f=d.isWindow?d.scrollLeft:d.offset.left;d=d.width;var e=a.left-b.collisionPosition.marginLeft,h=f-e,k=e+b.collisionWidth-d-f;b.collisionWidth>d?0<h&&0>=k?(c=a.left+h+b.collisionWidth-d-f,a.left+=h-c):a.left=0<k&&0>=h?
f:h>k?f+d-b.collisionWidth:f:0<h?a.left+=h:0<k?a.left-=k:a.left=g(a.left-e,a.left)},top:function(a,b){var c,d=b.within;d=d.isWindow?d.scrollTop:d.offset.top;var f=b.within.height,e=a.top-b.collisionPosition.marginTop,h=d-e,k=e+b.collisionHeight-f-d;b.collisionHeight>f?0<h&&0>=k?(c=a.top+h+b.collisionHeight-f-d,a.top+=h-c):a.top=0<k&&0>=h?d:h>k?d+f-b.collisionHeight:d:0<h?a.top+=h:0<k?a.top-=k:a.top=g(a.top-e,a.top)}},flip:{left:function(a,b){var c,d,e=b.within,g=e.offset.left+e.scrollLeft,h=e.width;
e=e.isWindow?e.scrollLeft:e.offset.left;var k=a.left-b.collisionPosition.marginLeft,m=k-e;k=k+b.collisionWidth-h-e;var l="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,u="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,r=-2*b.offset[0];0>m?(c=a.left+l+u+r+b.collisionWidth-h-g,(0>c||f(m)>c)&&(a.left+=l+u+r)):0<k&&(d=a.left-b.collisionPosition.marginLeft+l+u+r-e,(0<d||k>f(d))&&(a.left+=l+u+r))},top:function(a,b){var c,d,e=b.within,g=e.offset.top+e.scrollTop,h=e.height;
e=e.isWindow?e.scrollTop:e.offset.top;var k=a.top-b.collisionPosition.marginTop,m=k-e;k=k+b.collisionHeight-h-e;var l="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,p="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,q=-2*b.offset[1];0>m?(d=a.top+l+p+q+b.collisionHeight-h-g,a.top+l+p+q>m&&(0>d||f(m)>d)&&(a.top+=l+p+q)):0<k&&(c=a.top-b.collisionPosition.marginTop+l+p+q-e,a.top+l+p+q>k&&(0<c||k>f(c))&&(a.top+=l+p+q))}},flipfit:{left:function(){b.ui.position.flip.left.apply(this,
arguments);b.ui.position.fit.left.apply(this,arguments)},top:function(){b.ui.position.flip.top.apply(this,arguments);b.ui.position.fit.top.apply(this,arguments)}}};(function(){var a,c=document.getElementsByTagName("body")[0];var d=document.createElement("div");var f=document.createElement(c?"div":"body");var e={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};c&&b.extend(e,{position:"absolute",left:"-1000px",top:"-1000px"});for(a in e)f.style[a]=e[a];f.appendChild(d);e=c||
document.documentElement;e.insertBefore(f,e.firstChild);d.style.cssText="position: absolute; left: 10.7432222px;";d=b(d).offset().left;b.support.offsetFractions=10<d&&11>d;f.innerHTML="";e.removeChild(f)})()})(jQuery);
(function(b){b.widget("ui.autocomplete",{version:"1.10.4",defaultElement:"\x3cinput\x3e",options:{appendTo:null,autoFocus:!1,delay:300,minLength:1,position:{my:"left top",at:"left bottom",collision:"none"},source:null,change:null,close:null,focus:null,open:null,response:null,search:null,select:null},requestIndex:0,pending:0,_create:function(){var a,c,d,e=this.element[0].nodeName.toLowerCase(),g="textarea"===e;e="input"===e;this.isMultiLine=g?!0:e?!1:this.element.prop("isContentEditable");this.valueMethod=
this.element[g||e?"val":"text"];this.isNewMenu=!0;this.element.addClass("ui-autocomplete-input").attr("autocomplete","off");this._on(this.element,{keydown:function(e){if(this.element.prop("readOnly"))return a=!0,d=!0,c=!0,void 0;c=d=a=!1;var f=b.ui.keyCode;switch(e.keyCode){case f.PAGE_UP:a=!0;this._move("previousPage",e);break;case f.PAGE_DOWN:a=!0;this._move("nextPage",e);break;case f.UP:a=!0;this._keyEvent("previous",e);break;case f.DOWN:a=!0;this._keyEvent("next",e);break;case f.ENTER:case f.NUMPAD_ENTER:this.menu.active&&
(a=!0,e.preventDefault(),this.menu.select(e));break;case f.TAB:this.menu.active&&this.menu.select(e);break;case f.ESCAPE:this.menu.element.is(":visible")&&(this._value(this.term),this.close(e),e.preventDefault());break;default:c=!0,this._searchTimeout(e)}},keypress:function(d){if(a)return a=!1,(!this.isMultiLine||this.menu.element.is(":visible"))&&d.preventDefault(),void 0;if(!c){var e=b.ui.keyCode;switch(d.keyCode){case e.PAGE_UP:this._move("previousPage",d);break;case e.PAGE_DOWN:this._move("nextPage",
d);break;case e.UP:this._keyEvent("previous",d);break;case e.DOWN:this._keyEvent("next",d)}}},input:function(a){return d?(d=!1,a.preventDefault(),void 0):(this._searchTimeout(a),void 0)},focus:function(){this.selectedItem=null;this.previous=this._value()},blur:function(a){return this.cancelBlur?(delete this.cancelBlur,void 0):(clearTimeout(this.searching),this.close(a),this._change(a),void 0)}});this._initSource();this.menu=b("\x3cul\x3e").addClass("ui-autocomplete ui-front").appendTo(this._appendTo()).menu({role:null}).hide().data("ui-menu");
this._on(this.menu.element,{mousedown:function(a){a.preventDefault();this.cancelBlur=!0;this._delay(function(){delete this.cancelBlur});var c=this.menu.element[0];b(a.target).closest(".ui-menu-item").length||this._delay(function(){var a=this;this.document.one("mousedown",function(d){d.target===a.element[0]||d.target===c||b.contains(c,d.target)||a.close()})})},menufocus:function(a,c){if(this.isNewMenu&&(this.isNewMenu=!1,a.originalEvent&&/^mouse/.test(a.originalEvent.type)))return this.menu.blur(),
this.document.one("mousemove",function(){b(a.target).trigger(a.originalEvent)}),void 0;c=c.item.data("ui-autocomplete-item");!1!==this._trigger("focus",a,{item:c})?a.originalEvent&&/^key/.test(a.originalEvent.type)&&this._value(c.value):this.liveRegion.text(c.value)},menuselect:function(a,b){var c=b.item.data("ui-autocomplete-item"),d=this.previous;this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=d,this._delay(function(){this.previous=d;this.selectedItem=c}));
!1!==this._trigger("select",a,{item:c})&&this._value(c.value);this.term=this._value();this.close(a);this.selectedItem=c}});this.liveRegion=b("\x3cspan\x3e",{role:"status","aria-live":"polite"}).addClass("ui-helper-hidden-accessible").insertBefore(this.element);this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete")}})},_destroy:function(){clearTimeout(this.searching);this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete");this.menu.element.remove();
this.liveRegion.remove()},_setOption:function(a,b){this._super(a,b);"source"===a&&this._initSource();"appendTo"===a&&this.menu.element.appendTo(this._appendTo());"disabled"===a&&b&&this.xhr&&this.xhr.abort()},_appendTo:function(){var a=this.options.appendTo;return a&&(a=a.jquery||a.nodeType?b(a):this.document.find(a).eq(0)),a||(a=this.element.closest(".ui-front")),a.length||(a=this.document[0].body),a},_initSource:function(){var a,c,d=this;b.isArray(this.options.source)?(a=this.options.source,this.source=
function(c,d){d(b.ui.autocomplete.filter(a,c.term))}):"string"==typeof this.options.source?(c=this.options.source,this.source=function(a,g){d.xhr&&d.xhr.abort();d.xhr=b.ajax({url:c,data:a,dataType:"json",success:function(a){g(a)},error:function(){g([])}})}):this.source=this.options.source},_searchTimeout:function(a){clearTimeout(this.searching);this.searching=this._delay(function(){this.term!==this._value()&&(this.selectedItem=null,this.search(null,a))},this.options.delay)},search:function(a,b){return a=
null!=a?a:this._value(),this.term=this._value(),a.length<this.options.minLength?this.close(b):!1!==this._trigger("search",b)?this._search(a):void 0},_search:function(a){this.pending++;this.element.addClass("ui-autocomplete-loading");this.cancelSearch=!1;this.source({term:a},this._response())},_response:function(){var a=++this.requestIndex;return b.proxy(function(b){a===this.requestIndex&&this.__response(b);this.pending--;this.pending||this.element.removeClass("ui-autocomplete-loading")},this)},__response:function(a){a&&
(a=this._normalize(a));this._trigger("response",null,{content:a});!this.options.disabled&&a&&a.length&&!this.cancelSearch?(this._suggest(a),this._trigger("open")):this._close()},close:function(a){this.cancelSearch=!0;this._close(a)},_close:function(a){this.menu.element.is(":visible")&&(this.menu.element.hide(),this.menu.blur(),this.isNewMenu=!0,this._trigger("close",a))},_change:function(a){this.previous!==this._value()&&this._trigger("change",a,{item:this.selectedItem})},_normalize:function(a){return a.length&&
a[0].label&&a[0].value?a:b.map(a,function(a){return"string"==typeof a?{label:a,value:a}:b.extend({label:a.label||a.value,value:a.value||a.label},a)})},_suggest:function(a){var c=this.menu.element.empty();this._renderMenu(c,a);this.isNewMenu=!0;this.menu.refresh();c.show();this._resizeMenu();c.position(b.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next()},_resizeMenu:function(){var a=this.menu.element;a.outerWidth(Math.max(a.width("").outerWidth()+1,this.element.outerWidth()))},
_renderMenu:function(a,c){var d=this;b.each(c,function(b,c){d._renderItemData(a,c)})},_renderItemData:function(a,b){return this._renderItem(a,b).data("ui-autocomplete-item",b)},_renderItem:function(a,c){return b("\x3cli\x3e").append(b("\x3ca\x3e").text(c.label)).appendTo(a)},_move:function(a,b){return this.menu.element.is(":visible")?this.menu.isFirstItem()&&/^previous/.test(a)||this.menu.isLastItem()&&/^next/.test(a)?(this._value(this.term),this.menu.blur(),void 0):(this.menu[a](b),void 0):(this.search(null,
b),void 0)},widget:function(){return this.menu.element},_value:function(){return this.valueMethod.apply(this.element,arguments)},_keyEvent:function(a,b){this.isMultiLine&&!this.menu.element.is(":visible")||(this._move(a,b),b.preventDefault())}});b.extend(b.ui.autocomplete,{escapeRegex:function(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")},filter:function(a,c){var d=RegExp(b.ui.autocomplete.escapeRegex(c),"i");return b.grep(a,function(a){return d.test(a.label||a.value||a)})}});b.widget("ui.autocomplete",
b.ui.autocomplete,{options:{messages:{noResults:"No search results.",results:function(a){return a+(1<a?" results are":" result is")+" available, use up and down arrow keys to navigate."}}},__response:function(a){var b;this._superApply(arguments);this.options.disabled||this.cancelSearch||(b=a&&a.length?this.options.messages.results(a.length):this.options.messages.noResults,this.liveRegion.text(b))}})})(jQuery);
(function(b){b.widget("ui.menu",{version:"1.10.4",defaultElement:"\x3cul\x3e",delay:300,options:{icons:{submenu:"ui-icon-carat-1-e"},menus:"ul",position:{my:"left top",at:"right top"},role:"menu",blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.mouseHandled=!1;this.element.uniqueId().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length).attr({role:this.options.role,tabIndex:0}).bind("click"+
this.eventNamespace,b.proxy(function(a){this.options.disabled&&a.preventDefault()},this));this.options.disabled&&this.element.addClass("ui-state-disabled").attr("aria-disabled","true");this._on({"mousedown .ui-menu-item \x3e a":function(a){a.preventDefault()},"click .ui-state-disabled \x3e a":function(a){a.preventDefault()},"click .ui-menu-item:has(a)":function(a){var c=b(a.target).closest(".ui-menu-item");!this.mouseHandled&&c.not(".ui-state-disabled").length&&(this.select(a),a.isPropagationStopped()||
(this.mouseHandled=!0),c.has(".ui-menu").length?this.expand(a):!this.element.is(":focus")&&b(this.document[0].activeElement).closest(".ui-menu").length&&(this.element.trigger("focus",[!0]),this.active&&1===this.active.parents(".ui-menu").length&&clearTimeout(this.timer)))},"mouseenter .ui-menu-item":function(a){var c=b(a.currentTarget);c.siblings().children(".ui-state-active").removeClass("ui-state-active");this.focus(a,c)},mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(a,
b){var c=this.active||this.element.children(".ui-menu-item").eq(0);b||this.focus(a,c)},blur:function(a){this._delay(function(){b.contains(this.element[0],this.document[0].activeElement)||this.collapseAll(a)})},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(a){b(a.target).closest(".ui-menu").length||this.collapseAll(a);this.mouseHandled=!1}})},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".ui-menu").addBack().removeClass("ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".ui-menu-item").removeClass("ui-menu-item").removeAttr("role").removeAttr("aria-disabled").children("a").removeUniqueId().removeClass("ui-corner-all ui-state-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=b(this);a.data("ui-menu-submenu-carat")&&a.remove()});this.element.find(".ui-menu-divider").removeClass("ui-menu-divider ui-widget-content")},_keydown:function(a){function c(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$\x26")}var d=!0;switch(a.keyCode){case b.ui.keyCode.PAGE_UP:this.previousPage(a);break;case b.ui.keyCode.PAGE_DOWN:this.nextPage(a);break;case b.ui.keyCode.HOME:this._move("first","first",a);break;case b.ui.keyCode.END:this._move("last","last",a);break;case b.ui.keyCode.UP:this.previous(a);break;case b.ui.keyCode.DOWN:this.next(a);break;case b.ui.keyCode.LEFT:this.collapse(a);break;case b.ui.keyCode.RIGHT:this.active&&!this.active.is(".ui-state-disabled")&&this.expand(a);break;case b.ui.keyCode.ENTER:case b.ui.keyCode.SPACE:this._activate(a);
break;case b.ui.keyCode.ESCAPE:this.collapse(a);break;default:d=!1;var e=this.previousFilter||"";var g=String.fromCharCode(a.keyCode);var f=!1;clearTimeout(this.filterTimer);g===e?f=!0:g=e+g;var h=RegExp("^"+c(g),"i");e=this.activeMenu.children(".ui-menu-item").filter(function(){return h.test(b(this).children("a").text())});e=f&&-1!==e.index(this.active.next())?this.active.nextAll(".ui-menu-item"):e;e.length||(g=String.fromCharCode(a.keyCode),h=RegExp("^"+c(g),"i"),e=this.activeMenu.children(".ui-menu-item").filter(function(){return h.test(b(this).children("a").text())}));
e.length?(this.focus(a,e),1<e.length?(this.previousFilter=g,this.filterTimer=this._delay(function(){delete this.previousFilter},1E3)):delete this.previousFilter):delete this.previousFilter}d&&a.preventDefault()},_activate:function(a){this.active.is(".ui-state-disabled")||(this.active.children("a[aria-haspopup\x3d'true']").length?this.expand(a):this.select(a))},refresh:function(){var a=this.options.icons.submenu;var c=this.element.find(this.options.menus);this.element.toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length);
c.filter(":not(.ui-menu)").addClass("ui-menu ui-widget ui-widget-content ui-corner-all").hide().attr({role:this.options.role,"aria-hidden":"true","aria-expanded":"false"}).each(function(){var c=b(this),e=c.prev("a"),g=b("\x3cspan\x3e").addClass("ui-menu-icon ui-icon "+a).data("ui-menu-submenu-carat",!0);e.attr("aria-haspopup","true").prepend(g);c.attr("aria-labelledby",e.attr("id"))});c=c.add(this.element);c.children(":not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","presentation").children("a").uniqueId().addClass("ui-corner-all").attr({tabIndex:-1,
role:this._itemRole()});c.children(":not(.ui-menu-item)").each(function(){var a=b(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("ui-widget-content ui-menu-divider")});c.children(".ui-state-disabled").attr("aria-disabled","true");this.active&&!b.contains(this.element[0],this.active[0])&&this.blur()},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role]},_setOption:function(a,b){"icons"===a&&this.element.find(".ui-menu-icon").removeClass(this.options.icons.submenu).addClass(b.submenu);
this._super(a,b)},focus:function(a,b){this.blur(a,a&&"focus"===a.type);this._scrollIntoView(b);this.active=b.first();var c=this.active.children("a").addClass("ui-state-focus");this.options.role&&this.element.attr("aria-activedescendant",c.attr("id"));this.active.parent().closest(".ui-menu-item").children("a:first").addClass("ui-state-active");a&&"keydown"===a.type?this._close():this.timer=this._delay(function(){this._close()},this.delay);c=b.children(".ui-menu");c.length&&a&&/^mouse/.test(a.type)&&
this._startOpening(c);this.activeMenu=b.parent();this._trigger("focus",a,{item:b})},_scrollIntoView:function(a){var c,d,e,g,f,h;this._hasScroll()&&(c=parseFloat(b.css(this.activeMenu[0],"borderTopWidth"))||0,d=parseFloat(b.css(this.activeMenu[0],"paddingTop"))||0,e=a.offset().top-this.activeMenu.offset().top-c-d,g=this.activeMenu.scrollTop(),f=this.activeMenu.height(),h=a.height(),0>e?this.activeMenu.scrollTop(g+e):e+h>f&&this.activeMenu.scrollTop(g+e-f+h))},blur:function(a,b){b||clearTimeout(this.timer);
this.active&&(this.active.children("a").removeClass("ui-state-focus"),this.active=null,this._trigger("blur",a,{item:this.active}))},_startOpening:function(a){clearTimeout(this.timer);"true"===a.attr("aria-hidden")&&(this.timer=this._delay(function(){this._close();this._open(a)},this.delay))},_open:function(a){var c=b.extend({of:this.active},this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(a.parents(".ui-menu")).hide().attr("aria-hidden","true");a.show().removeAttr("aria-hidden").attr("aria-expanded",
"true").position(c)},collapseAll:function(a,c){clearTimeout(this.timer);this.timer=this._delay(function(){var d=c?this.element:b(a&&a.target).closest(this.element.find(".ui-menu"));d.length||(d=this.element);this._close(d);this.blur(a);this.activeMenu=d},this.delay)},_close:function(a){a||(a=this.active?this.active.parent():this.element);a.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false").end().find("a.ui-state-active").removeClass("ui-state-active")},collapse:function(a){var b=
this.active&&this.active.parent().closest(".ui-menu-item",this.element);b&&b.length&&(this._close(),this.focus(a,b))},expand:function(a){var b=this.active&&this.active.children(".ui-menu ").children(".ui-menu-item").first();b&&b.length&&(this._open(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this._move("next","first",a)},previous:function(a){this._move("prev","last",a)},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},isLastItem:function(){return this.active&&
!this.active.nextAll(".ui-menu-item").length},_move:function(a,b,d){var c;this.active&&(c="first"===a||"last"===a?this.active["first"===a?"prevAll":"nextAll"](".ui-menu-item").eq(-1):this.active[a+"All"](".ui-menu-item").eq(0));c&&c.length&&this.active||(c=this.activeMenu.children(".ui-menu-item")[b]());this.focus(d,c)},nextPage:function(a){var c,d,e;return this.active?(this.isLastItem()||(this._hasScroll()?(d=this.active.offset().top,e=this.element.height(),this.active.nextAll(".ui-menu-item").each(function(){return c=
b(this),0>c.offset().top-d-e}),this.focus(a,c)):this.focus(a,this.activeMenu.children(".ui-menu-item")[this.active?"last":"first"]())),void 0):(this.next(a),void 0)},previousPage:function(a){var c,d,e;return this.active?(this.isFirstItem()||(this._hasScroll()?(d=this.active.offset().top,e=this.element.height(),this.active.prevAll(".ui-menu-item").each(function(){return c=b(this),0<c.offset().top-d+e}),this.focus(a,c)):this.focus(a,this.activeMenu.children(".ui-menu-item").first())),void 0):(this.next(a),
void 0)},_hasScroll:function(){return this.element.outerHeight()<this.element.prop("scrollHeight")},select:function(a){this.active=this.active||b(a.target).closest(".ui-menu-item");var c={item:this.active};this.active.has(".ui-menu").length||this.collapseAll(a,!0);this._trigger("select",a,c)}})})(jQuery);function cq5forms_isArray(b){return"number"==typeof b.length&&b.item&&(!b.tagName||"SELECT"!=b.tagName.toUpperCase())}
xtag.register("sas-lightbox",{"extends":"div",accessors:{id:{attribute:{},set:function(b){function a(){var a=setInterval(function(){var c=jQuery("#"+b+" video").attr("poster");"undefined"!==typeof c&&!1!==c&&(clearInterval(a),jQuery("#poster"+b).attr("src",c))},250)}var c,d=jQuery(this);(function(){var e=setInterval(function(){jQuery("#"+b+" video").length&&"undefined"!==typeof bc&&(clearInterval(e),c=document.querySelector("#"+b+" video"),d.has("img[src^\x3d'/etc/designs/default/0.gif']")&&a(),c.onplay=
function(){jQuery(this).is(":visible")?c.play():c.pause()},jQuery("#"+b).on("show",function(){c.play()}),jQuery("#"+b).on("hide",function(){0<c.readyState&&(c.pause(),c.currentTime=0)}))},500)})()}}}});
xtag.register("sas-imageajax",{"extends":"div",lifecycle:{inserted:function(){function b(b,c,d){if(c.hasClass("is-hidden"))if(d){var e=a(c);-1<e.indexOf("?")&&(e=e.substring(0,e.indexOf("?")));e=e+"?"+(new Date).getTime();d=$("\x3cimg\x3e");d.load(function(){var a=e,d=c.find("img");if("undefined"!==typeof d.attr("src"))d.attr("src",a);else if(d=c.find("div.bg"),"undefined"!==typeof d.css("background-image")){var f=d.css("background-image"),g=f.replace('url("',"").replace('")',"");a=f.replace(g,a);
d.css("background-image",a)}b.addClass("is-hidden");c.removeClass("is-hidden")});d.attr("src",e)}else b.addClass("is-hidden"),c.removeClass("is-hidden")}function a(a){var b=a.find("img"),c="";"undefined"!==typeof b.attr("src")?c=b.attr("src"):"undefined"!==typeof a.css("background-image")&&(c=a.css("background-image").replace('url("',"").replace('")',""));return c}var c=jQuery(this),d=c.closest("div.surroundingDiv"),e=d.find("div.placeholderImage"),g=$("\x3cimg\x3e");g.load(function(){"undefined"!==
typeof d.attr("data-viewport")?new Waypoint.Inview({element:d,entered:function(a){var c=this.element;a=c.find("div.placeholderImage");c=c.find("div.ajaxImage");b(a,c,!0)},exited:function(a){var c=this.element;a=c.find("div.placeholderImage");c=c.find("div.ajaxImage");b(c,a,!1)}}):b(e,c,!1)});var f=a(c);""!=f&&g.attr("src",f)}}});
xtag.register("industry-selector",{"extends":"select",lifecycle:{inserted:function(){var b=!1;$('select[name\x3d"industry"]').is(":visible")&&(b=!0);1>this.selectedIndex&&!0===b&&(this.options[0].value="",this.selectedIndex=0);SAS.subscribe("/form/company/change",function(a,b){var c=$(a).closest("form").find("select[is*\x3d'industry-selector']"),e=$(a).closest("form").find("input[is*\x3d'x-company']");e=$.inArray(a,e);if(c[e]&&(e=$(c[e]).closest("div[class*\x3d'industry-form-row']"))){var g=function(a){if(!a)return!0;
SAS.companyAutofillData=null;jQuery.ajax({url:"/profile-extras/services/ext/constants/companies?term\x3d"+encodeURIComponent(a.trim()),dataType:"json",headers:{"X-SASProfile-AppKey":"ff00810c-7a3e-4dda-85b9-086f2c8c423a",Accept:"application/vnd.sas.profile-v3+json"},async:!1,success:function(a,b,c){a&&!jQuery.isEmptyObject(a)&&(SAS.companyAutofillData=a)},error:function(a,b,c){console.log("company list error: "+c)}});var b=!1;SAS.companyAutofillData&&0===SAS.companyAutofillData.indexOf(a.trim())&&
(b=!0);return b},f="";null!=b&&(f=b.value);f&&""!=f||(f=a.value);!f||""==f||g(f)?(e.hide(),1>c[0].selectedIndex&&(c[0].selectedIndex=0),$('select[name\x3d"industry"]').is(":visible")?c[0].options[0].value="":c[0].options[0].value="0"):(e.show(),1>c[0].selectedIndex&&(c[0].options[0].value="",c[0].selectedIndex=0))}})}}});
xtag.register("state-selector",{"extends":"select",lifecycle:{created:function(){var b=jQuery(this).closest("form").find("select[is*\x3d'state-selector']");b=$.inArray(this,b);var a=jQuery(this).closest("form").find("select[name*\x3d'country']");a[b]&&xtag.addEvent(a[b],"change",this.update(this))},inserted:function(){var b=jQuery(this).closest("form").find("select[is*\x3d'state-selector']");b=$.inArray(this,b);var a=jQuery(this).closest("form").find("select[name*\x3d'country']");a[b]&&((b=a[b].value)||
(b="us"),SAS.publish("/form/state/load",[this,b.toLowerCase()]))}},methods:{update:function(b){var a;return function(c){c=jQuery(c.target).val().toLowerCase();c!=a&&(a=c,SAS.publish("/form/state/load",[b,a]))}}}});
xtag.register("sas-include",{accessors:{path:{attribute:{},set:function(b){if(b&&b.length){var a=new XMLHttpRequest,c=this;if(!c.hasAttribute("data-matchMedia")||window.matchMedia(c.getAttribute("data-matchMedia")).matches){a.onreadystatechange=function(){var b=0;4==a.readyState&&(b=a.status);if(200==b)try{jQuery(c).replaceWith(a.responseText)}catch(h){console.log(h)}};var d="";if(c.hasAttribute("addSelector")||c.hasAttribute("addHash"))if(c.hasAttribute("addHash")&&(d="."+window.location.hash.replace("#",
"")),c.hasAttribute("addSelector"))for(var e=window.location.pathname,g=/\.(.*?)(?=\.)/g;selector=g.exec(e);)d+="."+selector[1];0<d.length?(b=b.replace(".html",d+".html"),b=c.hasAttribute("nocache")?b+("?"+Date.now()):b+("?q\x3d"+Date.now())):b+="?"+Date.now();try{a.open("GET",b,!0),a.send()}catch(f){console.log(f)}}}}}}});
xtag.register("sas-contenttargetingcontainer",{accessors:{path:{attribute:{},set:function(b){if(b&&b.length){var a=new XMLHttpRequest,c=this;a.onreadystatechange=function(){var b=0;4==a.readyState&&(b=a.status);if(200==b)try{jQuery(c).replaceWith(a.responseText)}catch(k){console.log(k)}};var d="",e="";if(c.hasAttribute("addSelector")){var g=c.getAttribute("addSelector");if("clickpath"==g.substring(0,9)){var f=g.substring(9);f=ContextHub.getStore("sas_aem_lastviewed_data").getLastViewedByCategoryValue(f);
0<f.length&&(d="."+f.replace("/","-"))}else switch(g){case "matchmedia":d=".screensize"+$(window).width();break;case "hash":d=".hashvalue"+window.location.hash.replace("#","");break;case "parameter":e=window.location.href.split("?")[1]}}b=0<d.length?b.replace(".html",d+".html")+"?q\x3d"+Date.now():"parameter"==g?b+("?"+Date.now()+"\x26"+e):b+("?"+Date.now());try{a.open("GET",b,!0),a.send()}catch(h){console.log(h)}}}}}});
xtag.register("x-company",{"extends":"input",lifecycle:{created:function(){jQuery(this).autocomplete({source:function(b,a){var c=document.getElementsByName("country")[0].value;b={term:b.term};c&&(b.country=c);$.ajax({url:"/profile-extras/services/ext/constants/companies",headers:{"X-SASProfile-AppKey":"ff00810c-7a3e-4dda-85b9-086f2c8c423a",Accept:"application/vnd.sas.profile-v3+json"},dataType:"json",data:b,success:function(b){a(b)},error:function(a,b,c){console.log("company list error: "+c)}})},
minLength:2,delay:10,appendTo:"div#company_autocomp",select:function(b,a){SAS.publish("/form/company/change",[this,a.item])},change:function(b,a){SAS.publish("/form/company/change",[this,a.item])}});jQuery(this).on("change",function(){SAS.publish("/form/company/change",[this,this.value])});setTimeout(function(){jQuery("input[is*\x3d'x-company']").each(function(){""!=this.value&&SAS.publish("/form/company/change",[this,this.value])})},200)}}});
SAS=function(b){b.fetchProfilePrefillData=function(){var a=(new Date).getTime();$.ajax({url:"/services/formPrefill?ck\x3d"+a+"\x26profile\x3dtrue",dataType:"json",async:!1,success:function(a,d,e){a&&!jQuery.isEmptyObject(a)?(b.profilePrefillData=a,console.debug("prefill data set:"+a)):console.debug(" prefill empty? - "+d)},error:function(a,b,e){console.debug("No form Prefill data -",b,e)},complete:function(a,b){console.debug("form prefill fetch is done.",b)}})};return b}(SAS||{});
xtag.register("sas-profile",{"extends":"span",lifecycle:{created:function(){console.debug("sasprofile tag created");SAS.profilePrefillData||SAS.fetchProfilePrefillData();console.debug("sasprofile created :",SAS.profilePrefillData)},inserted:function(){console.debug("sasprofile inserted");$(this).replaceWith(SAS.profilePrefillData[this.dataset.sasprofile])}}});
xtag.register("lastviewed-config",{"extends":"span",lifecycle:{inserted:function(){var b=jQuery(this);ContextHub.getStore("sas_aem_lastviewed_data").putLastViewed(b.attr("data-category"),b.attr("data-category-value"))}}});xtag.register("lastviewed-hidden",{"extends":"input",lifecycle:{inserted:function(){var b=jQuery(this),a=b.attr("class").substring(22).split(" ",1);a[0].length&&(a=ContextHub.getStore("sas_aem_lastviewed_data").getLastViewedByCategory(a[0]),a.length&&b.val(a))}}});
xtag.register("tag-category",{"extends":"span",lifecycle:{inserted:function(){try{var b=jQuery(this),a=b.attr("class").substring(14).split(" ",1);if(a[0].length){var c=ContextHub.getStore("sas_aem_lastviewed_data").getLastViewedByCategory(a);b.text(c)}}catch(d){console.log(d)}}}});
xtag.register("sas-recommendedcontent",{accessors:{path:{attribute:{},set:function(b){if(b&&b.length){var a=new XMLHttpRequest,c=this;a.onreadystatechange=function(){var b=0;4==a.readyState&&(b=a.status);if(200==b)try{jQuery(c).replaceWith(a.responseText)}catch(m){console.log(m)}};var d="";if(c.hasAttribute("addSelectorClickpath"))for(var e=c.getAttribute("addSelectorClickpath").trim().split(" "),g=0;g<e.length;g++){var f=e[g],h=ContextHub.getStore("sas_aem_lastviewed_data").getLastViewedByCategoryValue(f);
0<h.length&&(d+="."+f+h.replace("/","-"))}c.hasAttribute("addTimestamp")?(0<d.length&&(b=b.replace(".html",d+".html")),b+="?"+Date.now()):0<d.length&&(b=b.replace(".html",d+".html")+"?q\x3d"+Date.now());try{a.open("GET",b,!0),a.send()}catch(k){console.log(k)}}}}}});
xtag.register("sas-icon",{"extends":"div",lifecycle:{inserted:function(){var b=jQuery(this),a=b.find("svg");if("undefined"===typeof a.attr("style")){var c=b.attr("data-fillcolor"),d=b.attr("data-height"),e=b.attr("data-width"),g="";"undefined"!==typeof c&&(g+="fill: #"+c+"; ");"undefined"!==typeof d&&(g+="width:"+d+"px; ");"undefined"!==typeof e&&(g+="height:"+e+"px; ");a.attr("style",g)}b.removeClass("is-hidden")}}});
xtag.register("sas-downloadlink",{"extends":"a",lifecycle:{created:function(){var b=!1,a=$(this);$(a).click(function(c){0==b&&null!==jQuery.cookie("sasprefill")&&(b=!0,this.trackClick(a));c="/content/dam/"+a.attr("data-path");window.open(c,"_blank")})}},methods:{trackClick:function(b){var a=(new Date).getTime();$.ajax({url:"/services/formPrefill?ck\x3d"+a,dataType:"json",success:function(a,d,e){a&&!$.isEmptyObject(a)&&(a.email||a.emailAddress)&&(a.formid="clicktracker",a[":formstart"]=b.attr("data-page")+
"/jcr:content/clicktracker",a.EStarsEventId=b.attr("data-id"),a._charset_="UTF-8",$.ajax({url:window.location.pathname,type:"POST",data:a,success:function(a){console.log("click tracked")},error:function(a){console.log("click error")}}))},error:function(a,b,e){console.log("no prefill data")}})}}});
xtag.register("sas-dynamicselect",{"extends":"select",methods:{updateDropdown:function(b){return function(a){a=b.dataPath;var c=b.getParam();if(c){a=a+"?"+c;var d=new XMLHttpRequest;d.overrideMimeType("application/json");d.onload=function(){var a=JSON.parse(d.responseText);b.options.length=0;a.forEach(function(a){b.appendOption(b,a.text,a.value)});2>b.options.length?b.toggleFormRow(b,"none"):b.toggleFormRow(b,"block");"createEvent"in document?(a=document.createEvent("HTMLEvents"),a.initEvent("change",
!1,!0),b.dispatchEvent(a)):b.fireEvent("onchange")};try{d.open("GET",a,!0),d.send()}catch(e){console.log(e)}}else b.options.length=0,b.toggleFormRow(b,"none")}},appendOption:function(b,a,c){var d=document.createElement("option"),e=document.createAttribute("value");a=document.createTextNode(a);e.value=c;d.setAttributeNode(e);d.appendChild(a);b.appendChild(d)},toggleFormRow:function(b,a){b.parentNode.parentNode.style.display!==a&&(b.parentNode.parentNode.style.display=a)},getParam:function(){var b=
this.getWatched();if(b&&b.value){var a=b.getParam();a&&(a+="\x26");return a+b.name+"\x3d"+b.options[b.selectedIndex].value}return""},getWatched:function(){if(this.dataTarget)return document.getElementById(this.dataTarget)}},accessors:{dataTarget:{attribute:{},set:function(b){b&&(document.getElementById(b).addEventListener("change",this.updateDropdown(this)),this.toggleFormRow(this,"none"))}},dataPath:{attribute:{},set:function(b){var a=this;if(b&&b.length){var c=new XMLHttpRequest;c.overrideMimeType("application/json");
c.onload=function(){JSON.parse(c.responseText).forEach(function(b){a.appendOption(a,b.text,b.value)})};try{c.open("GET",b,!0),c.send()}catch(d){console.log(d)}}}}}});
xtag.register("sas-tabwrapper",{"extends":"div",lifecycle:{inserted:function(){function b(a){a.find(".carouselwrapper").each(function(){$(this).removeAttr("style");var b=$(this).attr("id");CarouselLoader["createSwipe_"+b]();if(0<a.find(".nav-buttons").length)CarouselLoader["initPrevNext_"+b]()})}function a(a){return a.replace(/([$%&()*+,./:;<=>?@\[\\\]^\{|}~])/g,"\\$1")}var c=$(this);$(window).on("hashchange",function(){var a=decodeURIComponent(window.location.hash);if(-1<a.indexOf("#")&&(""!==a?
(a="tabcontent_"+a.substr(1),a=c.find("ul.mod-tabs a[href\x3d'#"+a+"']").last()):a=c.find("ul.mod-tabs a").first(),1==a.length)){var b=a;a=b.closest("li");var d=c.find("ul.mod-tabs li.active"),e=c.find('[id\x3d"'+b.attr("href").substr(1)+'"]'),f=c.find("section.tabctrl-content:visible");b=b.parents(".tabwrapper").find(".tabctrl-collapse-wrapper");var g=!0;0<b.length&&b.hasClass("is-collapsed")&&(g=!1);!0===g&&(a.is(d)||(d.removeClass("active"),a.addClass("active")),f.removeClass("active"),e.addClass("active"))}});
c.find("ul.mod-tabs a").bind("click.tabwrapper",function(a){a.preventDefault();var b=$(this);a=b.closest("li");var d=c.find("ul.mod-tabs li.active");b=c.find('[id\x3d"'+b.attr("href").substr(1)+'"]');var e=c.find("section.tabctrl-content:visible");a.is(d)||(d.removeClass("active"),a.addClass("active"),location.hash=encodeURIComponent(a.attr("id").substr(3)));e.removeClass("active");b.addClass("active");$(this).parents(".tabwrapper").find(".tabctrl-collapse-wrapper").length&&(a=$(this).parents(".tabwrapper").find(".tabctrl-collapse-wrapper"),
a.hasClass("is-collapsed")&&a.removeClass("is-collapsed"))});var d=c.find("ul.mod-tabs li:first"),e=c.find("section.tabctrl-content:first"),g=!1;c.find("div.tabctrl-collapse-wrapper").length&&(c.find("button.collapse-close").click(function(){c.find("div.tabctrl-collapse-wrapper").addClass("is-collapsed");c.find("section.tabctrl-content").removeClass("active");c.find("ul.mod-tabs li.active").removeClass("active")}),g=!0);if(!1===g){g=decodeURIComponent(window.location.hash).substring(1);var f=decodeURIComponent(window.location.hash)+
"scroll";"tab"!==g&&$(a("#li_"+g)).length?(c.find("ul.mod-tabs li:first").removeClass("active"),d=c.find("#li_"+g),e=c.find("#tabcontent_"+g)):c.find(a(f)).length&&(g=c.find(f),g.parents("section").length&&(e=g.parents("section"),d=$("#li_"+e[0].id.substr(11))));d.addClass("active");0<c.find(".contentcarousel").length&&b(c);c.find("section.tabctrl-content").removeClass("active");e.addClass("active")}else 0<c.find(".contentcarousel").length&&b(c),c.find("section.tabctrl-content").removeClass("active");
c.find("ul.mod-tabs").removeAttr("style");c.find("div.mod-tabs-content").removeAttr("style")}}});xtag.register("sas-field-prefill",{"extends":"input",accessors:{dataWs:{attribute:{},set:function(b){if(b&&b.length){var a=new XMLHttpRequest,c=this;a.onreadystatechange=function(){var b=0;4==a.readyState&&(b=a.status);if(200==b)try{c.value=a.responseText}catch(e){console.log(e)}};b+="?"+Date.now();try{a.open("GET",b,!0),a.withCredentials=!0,a.send()}catch(d){console.log(d)}}}}}});
jQuery.fn.cancelFormSubmit=function(b){jQuery("input.form_button_submit").click(function(a){if(0<jQuery(this).parents("form").has("#cancelformsubmit").length)return b&&alert(b),a.preventDefault(),!1})};jQuery.fn.moveFormIntro=function(){var b=jQuery("#formintrotext").text(),a=jQuery("#formintrotext").html();""===b.trim()?jQuery("#formintrotext").hide():0<jQuery("#form-intro").length&&(jQuery("#form-intro").first().html(a),jQuery("#form-intro").first().show(),jQuery("#formintrotext").hide())};
jQuery.fn.closeEventInfo=function(){jQuery(".event-closed").closest("form").hide();jQuery(".event-closed").show()};function getUrlParams(){var b=[],a,c=window.location.href.slice(window.location.href.indexOf("?")+1).split("\x26");var d=c.length;for(a=0;a<d;a+=1){var e=c[a].split("\x3d");b.push(e[0]);b[e[0]]=e[1]}return b}function getHostName(){return(""+window.location).match(/^https?:\/\/[^\/]+/)}jQuery(document).ready(function(){jQuery("body").moveDescriptions()});
jQuery.fn.moveDescriptions=function(){jQuery("div.form_row_description").filter(function(a){return 0<jQuery("span",this).length}).each(function(a){a=jQuery(this).find("span").text();a=jQuery('\x3cspan class\x3d"form_row_description"\x3e'+a+"\x3c/span\x3e");jQuery(this).parent().find("div.form_leftcol").find("label").after(a);jQuery(this).hide()});var b="this field is required";jQuery("div.form_leftcolmark:contains('*')").each(function(a){jQuery(this).prev("div.form_leftcollabel").find("label").append('\x3cspan class\x3d"required"\x3e*\x3c/span\x3e');
b=jQuery(this).parent().parent().parent().find("div.form_error").text();jQuery(this).hide();var c=jQuery('\x3cspan class\x3d"form_error"\x3e'+b+"\x3c/span\x3e");b&&jQuery(this).closest("div.form_row").find("input,select,textarea").each(function(a){jQuery(this).last().after(c);jQuery(this).addClass("required")})});jQuery("div.form_error:parent").hide()};"undefined"==typeof SAS&&(SAS={});"undefined"==typeof SAS.forms&&(SAS.forms={});
SAS.forms.isFormEmailOptedIn=function(b,a){a=a||"email";b=b.$parent()[a].$value();return isOptedIn(b)};function isOptedIn(b){if(!b)return!1;var a=!1;jQuery.ajax({url:"/services/optInVerification?email\x3d"+b,dataType:"json",async:!1,success:function(b,d,e){b&&(a=b)},error:function(a,b,e){}});return a}function isInputTypeClickable(b){return b&&("radio"===b||"checkbox"===b)}
function createEvent(b,a,c,d){d=jQuery.Event(b,{});return jQuery.Event(b,{newValue:c,oldValue:a,propertyName:"value",originalEvent:d})}
jQuery(function(b){b(document).ready(function(){var a=b('input:hidden[name\x3d":formstart"]');if(!(void 0===a||null===a||1>a.length)){a=jQuery.browser.version;var c=!1;!jQuery.browser.msie||"8.0"!=a&&"7.0"!=a||(c=!0);0<b("p.form_error").length||(c&&(b(":checkbox").each(function(){b(this).prop("checked",!1)}),b(":radio").each(function(){b(this).prop("checked",!1)})),b("select").each(function(){if(null==b(this).val()||c)b(this).removeAttr("selected"),b(this)[0].selectedIndex=0}))}})});
jQuery(function(b){SAS.subscribe("/form/state/load",function(a,c){var d=getDropDownListToUse();b.ajax({url:"/services/statelist.json",data:{countryVal:c,dropPath:d},dataType:"json",async:!1,success:function(b,c,d){populateStates(b,a)},error:function(b,c,d){jQuery(a).find("option").remove()}})})});
function getDropDownListToUse(){if("undefined"===typeof SAS.forms.dropdownListPath||""===SAS.forms.dropdownListPath)SAS.forms.dropdownListPath="/etc/acs-commons/lists/statedropdowns";return SAS.forms.dropdownListPath}
function populateStates(b,a){a=jQuery(a);var c=a.val();a.html("");if(void 0!==b&&null!==b){for(var d,e=document.getElementsByTagName("LABEL"),g=0;g<e.length;g++)-1<e[g].htmlFor.indexOf("_state")&&(d=e[g]);null!=d&&(e=b[0],e.value&&"State"===e.value&&(g=d.innerHTML.indexOf('\x3cspan class\x3d"required"\x3e'),-1<g?d.innerHTML=e.text+d.innerHTML.substring(g):d.innerText=e.text));"State"===b[0].value&&(b=b.splice(1,b.length));b.forEach(function(b){var d=b.value;(b=b.text)||(b=d);b=new Option(b,d);c===
d&&jQuery(b).prop("selected",!0);a.append(b)})}};