(function(){var a={},c=new Map,b=Element.prototype.matches||Element.prototype.msMatchesSelector,d=NodeList.prototype.forEach||Array.prototype.forEach,h=String.prototype.startsWith||function(a,b){return this.substr(b||0,a.length)===a};a.bind=function(a,b){var q=c.get(a);q||(q=new Set,c.set(a,q));q.add(b);d.call(document.querySelectorAll(a),function(d){n(d,a,b)})};a.find=function(a,d){g(a,function(a){if(b.call(a,d))return a});return null};a.findAll=function(a,d){var c=[];g(a,function(a){b.call(a,d)&&
c.push(a)});return c};(new MutationObserver(function(a){a.forEach(function(a){e(a.addedNodes,k);e(a.removedNodes,m)})})).observe(document.body,{attributes:!1,childList:!0,subtree:!0,characterData:!1});var e=function(a,b){d.call(a,function(a){a.nodeType==Node.ELEMENT_NODE&&g(a,b)})},g=function(a,b){var d=new Set;d.add(a);d.forEach(function(a){b(a);for(var c=0;c<a.children.length;c++)d.add(a.children[c]);d["delete"](a)})},k=function(a){c.forEach(function(d,c){b.call(a,c)&&d.forEach(function(d){b.call(a,
c)&&n(a,c,d)})})},m=function(a){a["x-rava"]&&a["x-rava"].forEach(function(b){l(a,"removed",b)})},n=function(b,d,c){if(!c.scoped||c.target.contains(b)){var e=c.data||{},k=b["x-rava"];k||(k=new Set,b["x-rava"]=k);k.has(c)?l(b,"added",c,e):(k.add(c),"function"===typeof e&&(e=e.call(b)),Object.getOwnPropertyNames(c).forEach(function(k){if("events"===k){var g=e,q=c.events,u=c.target||b,p;for(p in q){var m=q[p];if("function"===typeof m)b.addEventListener(p,f(m,u,g));else{var l={};l.scoped=h.call(p.trim(),
":scope");l.target=b;l.events=m;l.data=g;m=p.replace(":scope",d).trim();a.bind(m,l)}}}if("methods"===k){g=c[k];for(var n in g)b[n]=g[n].bind(b)}if("callbacks"===k){k=e;n=c.callbacks;for(var t in n)q=n[t],"object"===typeof q&&(g={},g.scoped=h.call(t.trim(),":scope"),g.target=c.target||b,g.callbacks=q,g.data=k,q=t.replace(":scope",d).trim(),a.bind(q,g))}}),c.callbacks&&(l(b,"created",c,e),l(b,"added",c,e)))}},l=function(a,b,d,c){d.callbacks&&d.callbacks[b]&&d.callbacks[b].call(d.target||a,c,a)},f=function(a,
b,d){return function(c){a.call(b,c,d)}};"function"===typeof define&&define.amd?define(a):"undefined"!==typeof module&&module.exports?module.exports={rava:a}:window.rava=a})();
rava.bind(".accordion",{callbacks:{created:function(){null!=window.location.hash&&$(this).find(window.location.hash+"scroll").toggleClass("is-active").next().toggleClass("is-open")}},events:{":scope .accordion-title":{click:function(a){$(this).find(".accordion-title").toggleClass("is-active").next().toggleClass("is-open");$(this).find(".accordion-title").hasClass("is-active")&&(window.location.hash=$(this).find(".accordion-title").attr("id").replace("scroll",""))}}}});
rava.bind(".accordionwrapper",{events:{":scope .accordionbuttonexpand":{click:function(){this.toggle(!0)}},":scope .accordionbuttoncompress":{click:function(){this.toggle(!1)}}},methods:{toggle:function(a){$(this).find(".accordion-title").toggleClass("is-active",a).next().toggleClass("is-open",a)}}});jQuery(document).ready(function(){SAS.Utils.scrollToHash()});
jQuery(function(a){a(document).ready(function(){var c=jQuery.cookie("sassimid");a("a[href]").each(function(a,d){null!==d.href.match(/cvent\.com/i)&&(c||(c="999999"),console.log("rewriting cvent url"),null!==d.href.match(/\?/)?d.href=d.href+"\x26Refid\x3d"+c:d.href=d.href+"?Refid\x3d"+c)})})});
(function(a){var c=a("#headersuggest");if(c.length){var b=c.data("suggesturl")+"?echoParams\x3dall\x26wt\x3djson";a('input[name\x3d"q"]').autocomplete({minLength:1,delay:0,appendTo:c,source:function(d,c){a.ajax({url:b,dataType:"json",data:{q:d.term},success:function(b){b=a.map(b.suggest.mySuggester,function(a){return a.suggestions});b=a.map(b,function(a){return a.term});c(_.uniq(b))}})}})}})(jQuery);
jQuery(function(a){a(document).ready(function(){a(".tabctrl").each(function(){function c(b){b.find(".carouselwrapper").each(function(){a(this).removeAttr("style");var d=a(this).attr("id");CarouselLoader["createSwipe_"+d]();if(0<b.find(".nav-buttons").length)CarouselLoader["initPrevNext_"+d]()})}var b=a(this);b.find(".mod-tabs a").bind("click.tabctrl",function(){var d=a(this),c=d.closest("li"),e=b.find(".mod-tabs li.active");d=b.find(d.attr("href"));var h=b.find(".tabctrl-content:visible");c.is(e)||
(e.removeClass("active"),c.addClass("active"),location.hash=c.attr("id").substr(3).replace(/tab$/,""));h.removeClass("active");d.addClass("active");0<a(this).parents(".tabctrl").find(".tabctrl-collapse-wrapper").length&&(c=a(this).parents(".tabctrl").find(".tabctrl-collapse-wrapper"),c.hasClass("is-collapsed")&&(c.removeClass("is-collapsed"),b.find(".mod-tabs-content").css("height","auto"),b.find(".mod-tabs-content").height(b.find(".tabctrl-content:visible").height())));return!1});a(window).on("hashchange",
function(){var a=window.location.hash;if(-1==a.indexOf("#m\x3d")){var d=""!==a?b.find(".mod-tabs a[href\x3d'"+a+"tab']").last():b.find(".mod-tabs a").first();if(1==d.length){a=d.closest("li");var c=b.find(".mod-tabs li.active"),e=b.find(d.attr("href")),h=b.find(".tabctrl-content:visible");d=d.parents(".tabctrl").find(".tabctrl-collapse-wrapper");var f=!0;0<d.length&&d.hasClass("is-collapsed")&&(f=!1);1==f&&(a.is(c)||(c.removeClass("active"),a.addClass("active")),h.removeClass("active"),e.addClass("active"))}}});
var d=b.find(".mod-tabs li:first"),h=b.find(".tabctrl-content:eq(0)"),e=!1;0<b.find(".tabctrl-collapse-wrapper").length&&(b.find(".collapse-close").click(function(){a(this).parents(".tabctrl-collapse-wrapper").addClass("is-collapsed");b.find(".tabctrl-content").removeClass("active");b.find(".mod-tabs li.active").removeClass("active")}),e=!0);0==e?(e=window.location.hash.substring(1).toLowerCase()+"tab",""!==e&&"tab"!==e&&jQuery(SAS.Utils.escapeSelector("#"+e)).length?(b.find(".mod-tabs li:first").removeClass("active"),
d=b.find("#li_"+e),h=b.find("#"+e)):jQuery(SAS.Utils.escapeSelector(window.location.hash.toLowerCase()+"scroll")).length&&(e=jQuery(window.location.hash.toLowerCase()+"scroll"),e.parents("section[id$\x3d'tab']").length&&(h=e.parents("section[id$\x3d'tab']"),d=jQuery("#li_"+h[0].id))),d.addClass("active"),0<b.find(".contentcarousel").length&&c(b),b.find(".tabctrl-content").removeClass("active"),h.addClass("active")):(0<b.find(".contentcarousel").length&&c(b),b.find(".tabctrl-content").removeClass("active"));
b.find(".mod-tabs").removeAttr("style");b.find(".mod-tabs-content").removeAttr("style")})})});
jQuery(function(a){a(document).ready(function(){!a(".cq-wcm-edit").length&&jQuery(".container.has-video").length&&(-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")&&a("html").addClass("safari"),a("body").addClass("bgvideo"),a(".background-video").each(function(){var c=a(this).attr("id");try{if(bc(document.getElementById(c)),a("html.no-touch").length)if(-1!=navigator.userAgent.indexOf("Firefox"))videojs(c).ready(function(){this.play()});else videojs(c).on("loadedmetadata",
function(){this.play()})}catch(b){}}),a(".has-video").addClass("ready"))})});
jQuery(document).ready(function(a){Object.keys=Object.keys||function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),d="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),h=d.length;return function(c){if("object"!=typeof c&&"function"!=typeof c||null===c)throw new TypeError("Object.keys called on a non-object");var e=[],k;for(k in c)a.call(c,k)&&e.push(k);if(b)for(k=0;k<h;k++)a.call(c,d[k])&&e.push(d[k]);
return e}}()});jQuery(document).ajaxStop(function(){jQuery("ul.listOfItems").each(function(a,c){a=jQuery(c).data("groupLimit");0<a&&jQuery(c).find("li.listItem:visible").length>a&&jQuery(c).find("li.listItem:visible").slice(a).css({display:"none"})})});
jQuery(document).ready(function(a){var c="";window.location.hash&&-1<window.location.hash.indexOf("#filterlist\x3d")&&(c=window.location.hash.slice(12).replace(/[^a-z0-9_-]/gi,""));a("ul.listOfItems").each(function(b,d){d=a(d);b=d.data("groupLimit");d=d.find("li.listItem:visible");0<b&&d.length>b&&d.slice(b).css({display:"none"})});a(".listgroup").each(function(){function b(b){var d;f.children().each(function(){null!=a(this).attr("id")&&(d=a(this).attr("id"))});a(!0===b?"ul.listOfItems":"#"+d+" ul.listOfItems").each(function(d,
c){var e=a(c);d=e.attr("displayfirstcount");c=0;!0===b?c=parseInt(d):null!=f.find(".btn a").attr("batchSize")&&(c=parseInt(d)+f.counter);e=e.find("li.listItem:visible");0<d&&(e.length>c?e.slice(c).css({display:"none"}):f.find(".btn span").addClass("disabled"))})}function d(d){if(null!=f.filterDropDowns)for(var c=0,p=Object.keys(f.filterDropDowns),m=p.length;c<m;c++)a(this).parent().hasClass(p[c])&&(f.filterDropDowns[p[c]]=a(this).attr("data-tagvalue"),a(this).siblings("li").removeClass("selected"),
a(this).addClass("selected"),window.location.hash="filterlist\x3d"+a(this).attr("data-tagvalue"));f.find("ul.listOfItems li").removeAttr("style");f.find("ul.listOfItems").hasClass("list-bricks")&&f.find("ul.listOfItems li.listItem").addClass("brick");if(null!=f.filterDropDowns){c=0;p=Object.keys(f.filterDropDowns);for(m=p.length;c<m;c++)h(f.filterDropDowns[p[c]]);c=f.find("span.list-group");1<c.length&&e(c);k();g(f)}f.find("ul.listOfItems").hasClass("list-bricks")&&r&&r.imagesLoaded(function(){r.masonry("destroy");
r.masonry({itemSelector:".brick"})});jQuery(this).parent("ul").hasClass("is-open")&&jQuery(this).parent("ul").toggleClass("is-open");b(d)}function h(a){a&&""!==a&&(f.find("ul.listOfItems li.listItem:not(."+a+")").css({display:"none"}),f.find("ul.listOfItems").hasClass("list-bricks")&&f.find("ul.listOfItems li.listItem:not(."+a+")").removeClass("brick"))}function e(b){b.each(function(b,c){0<a(c).siblings("ul").find("li.listItem:visible").length?(a(c).removeAttr("style"),a(c).parent().next("span.div-shadow").removeAttr("style")):
(a(c).css({display:"none"}),a(c).parent().next("span.div-shadow").css({display:"none"}))})}function g(b){b.find("ul.listOfItems").each(function(c,d){c=a(d).data("groupLimit");d=a(d).find("li.listItem:visible");0<c&&d.length>c&&(d.slice(c).css({display:"none"}),b.find("ul.listOfItems").hasClass("list-bricks")&&b.find("ul.listOfItems li.listItem:not(."+filter+")").removeClass("brick"))})}function k(){for(var a=0,b=Object.keys(f.filterDropDowns),c=b.length;a<c;a++)dropdownToProcess=f.find("ul."+b[a]),
dropdownToProcess.length&&""===f.filterDropDowns[b[a]]&&m(dropdownToProcess)}function m(b){var c=b.find("li");c.removeAttr("style");var d=1;c.each(function(b,c){b=a(c).attr("data-tagvalue");""!==b&&(f.find("ul.listOfItems li."+b+":visible").length?++d:a(c).css({display:"none"}))});1<d?b.removeClass("inactive"):b.addClass("inactive")}function n(){var a=f.find(".btn a").attr("batchSize");f.counter+=parseInt(a);d(!1)}function l(){f.find("ul.listOfItems").hasClass("list-bricks")&&f.find("ul.listOfItems li.listItem").addClass("brick");
if(f.find("div.filters").length){f.filterDropDowns={filterSelection1:f.find("ul.filterSelection1 li.filter_li").first().attr("data-tagvalue"),filterSelection2:f.find("ul.filterSelection2 li.filter_li").first().attr("data-tagvalue"),filterSelection3:f.find("ul.filterSelection3 li.filter_li").first().attr("data-tagvalue")};f.find("ul.filterSelection1 li.filter_li").first().addClass("selected");f.find("ul.filterSelection2 li.filter_li").first().addClass("selected");f.find("ul.filterSelection3 li.filter_li").first().addClass("selected");
k();for(var b=window.location.href.slice(window.location.href.indexOf("?")+1).split("\x26"),e=function(b,c){b.each(function(b,d){a(d).attr("data-tagvalue")==c[0]+c[1]&&(a(d).siblings("li").removeClass("selected"),a(d).addClass("selected"))})},h=0;h<b.length;h++){hash=b[h].split("\x3d");for(var g=0,m=Object.keys(f.filterDropDowns),l=m.length;g<l;g++)if(hash[0]==f.find("ul."+m[g]).attr("data-tagcategory")){f.filterDropDowns[m[g]]=hash[0]+hash[1];var v=f.find("ul."+m[g]+" li");e(v,hash)}}d(!0);f.find("li.filter_li").on("click",
d);f.find(".btn a").on("click",n);f.find("button.filter-toggle").click(function(){var b=a(this).siblings("ul").attr("class");f.find("button.filter-toggle").siblings("ul").each(function(c,d){b!=d.className&&a(d).removeClass("is-open")});jQuery(this).siblings("ul").toggleClass("is-open")});""!==c&&a('li.filter_li[data-tagvalue\x3d"'+c+'"]').each(d)}f.find("ul.listOfItems").hasClass("list-bricks")&&(r=f.find("ul.listOfItems"),r.imagesLoaded(function(){r.masonry({itemSelector:".brick",isResizable:"true"});
r.addClass("loaded")}))}var f=a(this),r=null;f.counter=0;if(f.find("div.syncmode").hasClass("sync"))f.find("div.filters").length||f.find("ul.listOfItems").hasClass("list-bricks")?l():(b(!0),f.find(".btn a").on("click",n));else f.on("listloaded",function(){f.find("div.filters").length||f.find("ul.listOfItems").hasClass("list-bricks")?l():(b(!0),f.find(".btn a").on("click",n))})})});
var SAS=function(a){a.setcookiereg=function(a,b,d){jQuery.cookie.raw=!0;var c=jQuery.cookie(a),e={},g=[];if(null!=c&&""!=c){e=JSON.parse(c);e=JSON.parse(e);c=e.interactionid;var k=c[b];null!=k&&(g=k);g.push(d)}else c={},g[0]=d;c[b]=g;e.interactionid=c;b=JSON.stringify(e);b=JSON.stringify(b);jQuery.cookie(a,b,{path:"/"})};a.ajaxcheckreg=function(c){var b=jQuery("#email"+c).val(),d=jQuery("#"+c).attr("data-ajax");d=d+"?checkemail\x3d"+b;var h=d.substring(0,d.indexOf("/_jcr_content"))+".html";jQuery.ajax({url:d,
type:"GET",success:function(b){if("false"===b)jQuery("#alert"+c).removeClass("is-hidden");else{var d="sasevents",e="11234",m="noemail",n=null,l=b.split("+");2<l.length&&(e=l[0],n=e.split("_"),m=l[1],d=l[2],l=l[3],5<l.length&&(h=b.substring(b.indexOf(l))));if(null!=n)for(var f in n)a.setcookiereg(d,n[f],m);else a.setcookiereg(d,e,m);""!=h&&window.location.replace(h)}},dataType:"html"}).fail(function(a,b){console.log("Request failed: "+b)})};a.subscribe("/show/form/alreadyregistered",function(a){jQuery(a).removeClass("is-hidden")});
jQuery(".already_registered_email").each(function(){var c=jQuery(this).attr("id");c=c.substring(5);jQuery(this).keydown(function(b){13===b.keyCode&&a.ajaxcheckreg(c)})});return a}(SAS||{});
xtag.register("sas-twitter",{"extends":"a",lifecycle:{created:function(){var a=document.createElement("script");a.type="text/javascript";a.defer=!0;a.src="https://platform.twitter.com/widgets.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c);var b=jQuery(this);(function(){var a=setInterval(function(){clearInterval(a);(b.hasClass("twitter-timeline-error")||b.hasClass("twitter-grid-error"))&&b.removeClass("hide")},3E3)})()}}});
jQuery(function(a){a(document).ready(function(){a(".tabwrapper").each(function(){function c(b){b.find(".carouselwrapper").each(function(){a(this).removeAttr("style");var c=a(this).attr("id");CarouselLoader["createSwipe_"+c]();if(0<b.find(".nav-buttons").length)CarouselLoader["initPrevNext_"+c]()})}var b=a(this);a(window).on("hashchange",function(){var a=decodeURIComponent(window.location.hash);if(-1<a.indexOf("#")&&(""!==a?(a="tabcontent_"+a.substr(1),a=b.find("ul.mod-tabs a[href\x3d'#"+a+"']").last()):
a=b.find("ul.mod-tabs a").first(),1==a.length)){var c=a;a=c.closest("li");var d=b.find("ul.mod-tabs li.active"),e=b.find('[id\x3d"'+c.attr("href").substr(1)+'"]'),f=b.find("section.tabctrl-content:visible");c=c.parents(".tabwrapper").find(".tabctrl-collapse-wrapper");var g=!0;0<c.length&&c.hasClass("is-collapsed")&&(g=!1);!0===g&&(a.is(d)||(d.removeClass("active"),a.addClass("active")),f.removeClass("active"),e.addClass("active"))}});b.find("ul.mod-tabs a").bind("click.tabwrapper",function(c){c.preventDefault();
var d=a(this);c=d.closest("li");var e=b.find("ul.mod-tabs li.active");d=b.find('[id\x3d"'+d.attr("href").substr(1)+'"]');var g=b.find("section.tabctrl-content:visible");c.is(e)||(e.removeClass("active"),c.addClass("active"),location.hash=encodeURIComponent(c.attr("id").substr(3)));g.removeClass("active");d.addClass("active");a(this).parents(".tabwrapper").find(".tabctrl-collapse-wrapper").length&&(c=a(this).parents(".tabwrapper").find(".tabctrl-collapse-wrapper"),c.hasClass("is-collapsed")&&c.removeClass("is-collapsed"))});
var d=b.find("ul.mod-tabs li:first"),h=b.find("section.tabctrl-content:first"),e=!1;b.find("div.tabctrl-collapse-wrapper").length&&(b.find("a.collapse-close").click(function(){b.find("div.tabctrl-collapse-wrapper").addClass("is-collapsed");b.find("section.tabctrl-content").removeClass("active");b.find("ul.mod-tabs li.active").removeClass("active")}),e=!0);if(!1===e){e=decodeURIComponent(window.location.hash).substring(1);var g=decodeURIComponent(window.location.hash)+"scroll";"tab"!==e&&a(SAS.Utils.escapeSelector("#li_"+
e)).length?(b.find("ul.mod-tabs li:first").removeClass("active"),d=b.find("#li_"+e),h=b.find("#tabcontent_"+e)):b.find(SAS.Utils.escapeSelector(g)).length&&(e=b.find(g),e.parents("section").length&&(h=e.parents("section"),d=a("#li_"+h[0].id.substr(11))));d.addClass("active");0<b.find(".contentcarousel").length&&c(b);b.find("section.tabctrl-content").removeClass("active");h.addClass("active")}else 0<b.find(".contentcarousel").length&&c(b),b.find("section.tabctrl-content").removeClass("active");b.find("ul.mod-tabs").removeAttr("style");
b.find("div.mod-tabs-content").removeAttr("style")})})});jQuery(function(a){a(document).ready(function(a){var b=CQ_Analytics.ClientContextMgr.getRegisteredStore("locstore");a(".conditionalcontainer").each(function(){function c(){var a=h.find("div.container"),c=a.attr("data-condition");if(""!==c&&b){var d=b.getProperty("address/country_code",!0);"undefined"!==typeof d&&c.contains(d)&&a.removeClass("is-hidden")}}var h=a(this);b&&b.addListener("update",c())})})});
SAS=function(a){var c=!1;a.submitForm=function(b){if(0==c)jQuery("input.form_button_submit").prop("disabled","disabled"),c=!0;else return!1;var d=jQuery("#"+b);b=d.find("input[name\x3d'formSubmissionType']");var h=d.find(".confirmationText");a.lastiid&&jQuery("#EStarsEventId").val(a.lastiid);if(b&&"async"==b.val())return jQuery.ajax({url:d.attr("action"),type:"POST",data:d.serialize(),success:function(a){var b=d.find("input[name\x3d'serviceAdapter']");null!=b&&0<b.length&&null!=a?d.replaceWith(a):
d.replaceWith(h.html());try{handlePostAsyncFormSubmit()}catch(k){console.log("post async handler method does not exist for the current design")}return!1},error:function(a){console.log(a.statusText+" "+a.responseText);return!1}}),!1;d.submit();b=ContextHub.getStore("sas_aem_forms_data");b.putRegistration(d)?(console.log("User registered for interaction: "+b.getEventID()),a.setcookiereg("sasevents",b.getEventID(),a.Utils.Base64.encode(b.getEmail()))):console.log("Error: registration cookie not written due to context hub issue")};
return a}(SAS||{});
function CurrentRequest(){function a(a,c){var d=null;b.length>=a&&null!=b[a]&&(d=b[a]);if(void 0===d||null===d)d=void 0!==c?c:"";return d}function c(a){return a.protocol+"://"+a.host+a.portPrefix+a.port}var b=(""+window.location).match(/^(https?):\/\/([^\/:]+):?(\d*)?(\/[^\?\.]+)?(\.[^\?]+)?(\?.*)?$/);this.protocol=a(1);this.host=a(2);this.port=a(3);this.portPrefix=0<this.port.length?":":"";this.page=a(4);this.selectors=a(5);this.params=a(6);this.newSelector=function(a){return c(this)+this.page+a};
this.newUrl=function(a){return void 0===a||null===a||1>a.length?c(this):c(this)+(/^\//.test(a)?"":"/")+a}}SAS=SAS||{};SAS.Utils=SAS.Utils||{};SAS.Utils.switchTab=function(a){var c=jQuery("#li_"+a);a=jQuery("section#"+a);var b=c.parents(".tabctrl");b.find(".mod-tabs li.active").removeClass("active");c.find(".tabctrl-content:visible").removeClass("active");c.addClass("active");b.find(c.first().attr("href")).addClass("active");a.addClass("active")};
SAS.Utils.escapeSelector=function(a){return a.replace(/([$%&()*+,./:;<=>?@\[\\\]^\{|}~])/g,"\\$1")};
SAS.Utils.scrollToHash=function(a){a=a||1E3;var c=decodeURIComponent(window.location.hash)+"scroll",b=jQuery(SAS.Utils.escapeSelector(c.toLowerCase()));b.parents("section[id$\x3d'tab']").length&&(currentContent=b.parents("section[id$\x3d'tab']"),SAS.Utils.switchTab(currentContent[0].id));setTimeout(function(){if(0<jQuery(SAS.Utils.escapeSelector(c)).length){var b=jQuery(c).offset().top-50;jQuery("html, body").animate({scrollTop:b},a,"swing")}},300);jQuery(".listgroup").trigger("listloaded")};
SAS.Utils.scrollToListGroup=function(a){if(!jQuery(a).parents(".subtabs").length&&location.pathname.replace(/^\//,"")==a.pathname.replace(/^\//,"")&&location.hostname==a.hostname){a=jQuery(a).attr("href")+"scroll";try{if(a.length){var c=jQuery(".header.fixed").length?jQuery(a).offset().top:jQuery(a).offset().top-150;jQuery("html, body").animate({scrollTop:c},1E3,"swing")}}catch(b){console.log(b.message)}}};
SAS.Utils.executeScrollToHash=function(){"undefined"!=typeof jmpDesign&&"function"==typeof jmpDesign.scrollToHash?jmpDesign.scrollToHash():"undefined"!=typeof pblsDesign&&"function"==typeof pblsDesign.scrollToHash?pblsDesign.scrollToHash():"undefined"!=typeof saswwwDesign&&"function"==typeof saswwwDesign.scrollToHash?saswwwDesign.scrollToHash():"undefined"!=typeof sascampaignsDesign&&"function"==typeof sascampaignsDesign.scrollToHash?sascampaignsDesign.scrollToHash():SAS.Utils.scrollToHash()};
SAS.Utils.executeScrollToListGroup=function(){"undefined"!=typeof jmpDesign&&"function"==typeof jmpDesign.scrollToListGroup?jmpDesign.scrollToListGroup(this):"undefined"!=typeof pblsDesign&&"function"==typeof pblsDesign.scrollToListGroup?pblsDesign.scrollToListGroup(this):"undefined"!=typeof saswwwDesign&&"function"==typeof saswwwDesign.scrollToListGroup?saswwwDesign.scrollToListGroup(this):"undefined"!=typeof sascampaignsDesign&&"function"==typeof sascampaignsDesign.scrollToListGroup?sascampaignsDesign.scrollToListGroup(this):
SAS.Utils.scrollToListGroup(this)};
jQuery(document).ready(function(){var a=jQuery("div.async-list"),c=[];jQuery.each(a,function(a,b){a=jQuery.ajax({url:jQuery(this).attr("data-url"),type:"GET",dataType:"html"});a.done(function(a){jQuery(b).replaceWith(a)});a.fail(function(a,c){jQuery(b).replaceWith("");console.log("Request failed: "+c)});c.push(a)});var b=function(){jQuery(this).toggleClass("show");jQuery(this).next("span.abstract").toggleClass("show");return!1};jQuery(".listgroup").on("click","a[href*\x3d'#']:not([href\x3d'#'])",SAS.Utils.executeScrollToListGroup);
jQuery("body").on("click","a[href*\x3d'#']:not([href\x3d'#'])",SAS.Utils.executeScrollToListGroup);jQuery(".listgroup").on("click","button.abstract-toggle",b);jQuery(".assetlist").on("click","button.abstract-toggle",b);a&&0===a.length?SAS.Utils.executeScrollToHash():jQuery.when.apply(null,c).then(function(){SAS.Utils.executeScrollToHash()})});